language: c
before_install:
    - sudo apt-get update
install:
    - sudo apt-get install rpm libluajit-5.1-dev libjsoncpp-dev
    - sudo apt-get install rpm libluajit-5.1-dev libjsoncpp-dev linux-headers-generic
before_script:
    - export KERNELDIR=/lib/modules/$(ls /lib/modules | sort | head -1)/build
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make package
    - cd ..
    - rm -rf build
    - mkdir build
    - cd build
    - cmake .. -DUSE_BUNDLED_JSONCPP=OFF -DUSE_BUNDLED_LUAJIT=OFF
    - make
    - make package
compiler:
    - gcc
    - clang
