language: c
env:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
install:
    - sudo apt-get -qq install g++-4.8
    - sudo apt-get install rpm linux-headers-generic
    - sudo apt-get purge libncurses5-dev cmake
before_script:
    - export KERNELDIR=/lib/modules/$(ls /lib/modules | sort | head -1)/build
script:
    - set -e
    - export CC="gcc-4.8"
    - export CXX="g++-4.8"
    - wget https://s3.amazonaws.com/download.draios.com/dependencies/cmake-3.3.2.tar.gz
    - tar -xzf cmake-3.3.2.tar.gz
    - cd cmake-3.3.2
    - ./bootstrap --prefix=/usr
    - make
    - sudo make install
    - cd ..
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - make VERBOSE=1
    - make package
    - cd ..
    - rm -rf build
    - pushd $(mktemp -d --tmpdir sysdig.XXXXXXXXXX)
    - wget https://github.com/open-source-parsers/jsoncpp/archive/0.10.2-p1.tar.gz
    - tar zxvf 0.10.2-p1.tar.gz
    - cd jsoncpp-0.10.2-p1
    - cmake -DBUILD_SHARED_LIBS=ON .
    - make
    - sudo make install
    - cd ..
    - wget https://s3.amazonaws.com/download.draios.com/dependencies/libb64-1.2.src.zip
    - unzip libb64-1.2.src.zip
    - cd libb64-1.2
    - make
    - sudo cp -r include/* /usr/local/include/
    - sudo cp src/libb64.a /usr/local/lib/
    - popd
    - rm -rf userspace/libsinsp/third-party/jsoncpp
    - sudo apt-get install libncurses5-dev libluajit-5.1-dev
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DUSE_BUNDLED_JSONCPP=OFF -DUSE_BUNDLED_LUAJIT=OFF -DUSE_BUNDLED_ZLIB=OFF -DUSE_BUNDLED_NCURSES=OFF -DUSE_BUNDLED_B64=OFF
    - make VERBOSE=1
    - make package
    - cd ..
    - test/sysdig_trace_regression.sh build/userspace/sysdig/sysdig build/userspace/sysdig/chisels $TRAVIS_BRANCH
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fdbc2356fb0ea2f15033
    on_success: change
    on_failure: always
    on_start: never