language: c
env:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release
before_install:
    - sudo apt-get update
install:
    - sudo apt-get install rpm libluajit-5.1-dev libjsoncpp-dev linux-headers-generic
before_script:
    - export KERNELDIR=/lib/modules/$(ls /lib/modules | sort | head -1)/build
script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - make
    - make package
    - cd ..
    - rm -rf build
    - pushd /tmp
    - wget http://download.draios.com/dependencies/zlib-1.2.8.tar.gz
    - tar -xzf zlib-1.2.8.tar.gz
    - cd zlib-1.2.8
    - ./configure
    - make
    - make install
    - popd
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DUSE_BUNDLED_JSONCPP=OFF -DUSE_BUNDLED_LUAJIT=OFF -DUSE_BUNDLED_ZLIB=OFF -DZLIB_PREFIX=/usr/local/include
    - make
    - make package
compiler:
    - gcc
    - clang
